### ISSUE TITLE
Als Project einen kompletten GitHub Projektlink erlauben

### ISSUE THREAD

**Issue by cmfcmf** [HPI-SWA-Teaching/SWT16-Project-05#10]
> Als User möchte ich im Issue Package Browser auch die komplette URL zum Repository eingeben können, die dann auf den Slug reduziert wird, da ich so schneller neue Squeak Packages in das Issue Management integrieren kann.

http unterstützen!
Eingabe ungültig anzeigen
(nach "github" suchen, nach ".git" suchen)

**Comment by frederike-ramin** [comment]
Warum bisher keine Tests: Bevor man manuell durchgeht, was die UI macht und "suche nach Button mit Namen saveButton + click" usw macht, sollte man sich eher das Morphic Testing Framework anschauen, um das einfacher und verständlicher- hinzubekommen.
