### ISSUE TITLE
Scopes des eingegebenen Tokens prüfen

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#13]
> Als User möchte ich, dass nach Eingabe des Tokens die Scopes überprüft werden und fehlerhafte Scopes gemeldet werden.

**Comment by frederike-ramin** [comment]
Nach Eingabe des Tokens sollten die Scopes überprüft werden und fehlerhafte Tokens / Scopes gemeldet werden.

**Comment by frederike-ramin** [comment]
Als User möchte ich klassenseitige Issues erstellen können, um allgemeine Aufgaben an der Klasse zu definieren.

**Comment by cmfcmf** [comment]
Jeder API Request sendet automatisch die authentifizierten Scopes des Tokens mit zurück. Beispielsweise ließe sich ein solcher Request bauen:

```
https://api.github.com/rate_limit?access_token=DasToken
```

Dann muss man nur noch den `X-OAuth-Scopes` Header überprüfen wie hier beschrieben: https://developer.github.com/v3/oauth/#scopes
