### ISSUE TITLE
Klassenseitige Issues erstellen

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#16]
> Als User möchte ich klassenseitige Issues genauso wie für Methoden erstellen können, um allgemeine Aufgaben an der Klasse zu definieren.

**Comment by cmfcmf** [comment]
@xasetl Das Kontextmenü für klassenseitige aktive Issues fehlt noch.

**Comment by xasetl** [comment]
steht das etwa auf der Karte? :P
ja, ist mir bewusst und wird noch gemacht.
