### ISSUE TITLE
Klassen-Issue-Icon

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#18]
> Als User möchte ich genauso wie bei den Methoden Icons angezeigt bekommen, um Issues bezüglich der Klasse sofort zu erkennen.

**Comment by xasetl** [comment]
erste Lösung
((PackageInfo allPackages detect: [:p | p includesClassNamed: aClassNameSymbol asString]) name).

zweite:
(Smalltalk classNamed: aClassNameSymbol) packageInfo name.

:)

**Comment by cmfcmf** [comment]
Sehr cool!!!!!111elf! 

_Jetzt noch deinen Code im Kommentar ordentlich mit Markdown formatieren und ich hab nichts mehr zu meckern_ :stuck_out_tongue_winking_eye:
