### ISSUE TITLE
"Issue Integration" statt "Issue Browser" in Menubar

### ISSUE THREAD

**Issue by cmfcmf** [HPI-SWA-Teaching/SWT16-Project-05#19]
> Als User möchte ich einen klareren Namen haben, der die Intention des Issue Package Browsers besser ausdrückt, damit die Issue Integration Einrichtung für mich einfacher wird.

**Comment by xasetl** [comment]
`TheWorldMenu registry copy do: [ :ea| (ea first = 'Issue Package Browser ') ifTrue: [TheWorldMenu registry remove: ea.]].`
da The World Menu class unregisterOpenCommand nicht funzt, hilft das, den Eintrag zu löschen

wann wird IssuePackageBrowser class initialize aufgerufen?

**Comment by cmfcmf** [comment]
@HPI-SWA-Teaching/2016-student-team-05 Ist das fertig?
