### ISSUE TITLE
Entscheiden, wie man die API Calls der GitHub API mock'en kann

### ISSUE THREAD

**Issue by cmfcmf** [HPI-SWA-Teaching/SWT16-Project-05#24]
> Als Entwickler möchte ich wissen, wie ich API Calls mocken kann, um unabhängig von GitHub zu werden.
- Idee 1: Einen MockWebClient von WebClient erben lassen und die http\* Methoden mocken
- Idee 2: Einen WebServer einschalten, den man dem WebClient als ProxyServer übergibt (RatPack?)

**Comment by fniephaus** [comment]
Hier der Link zu RatPack:
https://github.com/HPI-SWA-Teaching/RatPack2.0

**Comment by cmfcmf** [comment]
Ergebnisse:

| Tool | Anmerkungen |
| --- | --- |
| [RatPack](https://github.com/HPI-SWA-Teaching/RatPack2.0) | :-1: Kaum / keine Dokumentation. Ist irgendwie an eine Datenbank gebunden. Viele Dependencies |
| Selbstbau mit [KomHttpServer](http://www.squeaksource.com/KomHttpServer.html) | :+1: Funktioniert einfach. Dokumentation vorhanden. Weniger Dependencies als RatPack |
| Jegliche externe Tools außerhalb von Squeak | :-1: :-1: Erfordern erhöhten Einrichtungsaufwand -> Nachfolgende Teams werden also Probleme haben. Erfordern Dokumentation. |

Wir wählen also die Selbstbauvariante mit [KomHttpServer](http://www.squeaksource.com/KomHttpServer.html).

**Comment by cmfcmf** [comment]
Wir haben uns wie besprochen nun doch für den Nachbau mittels der `WebServer` Klasse entschieden. Der `KomHttpServer` wird nicht benötigt.
