### ISSUE TITLE
GitHub Fehler anzeigen

### ISSUE THREAD

**Issue by cmfcmf** [HPI-SWA-Teaching/SWT16-Project-05#29]
> Als User möchte ich den von GitHub zurückgegebenen Fehler angezeigt bekommen, wenn die GitHub API eine "falsche" Antwort gibt, egal um welche Request / Response es sich handelt, damit ich Fehler besser bemerke.

**Comment by xasetl** [comment]
als guard clause ist's ganz praktisch.
eine methode zum ausgeben der fehler im IssueManagement sollte angelegt werden

**Comment by xasetl** [comment]
hmm, da ploppen immer noch rote Vierecke auf. beim Auswählen des Icons wird nach issues gefragt.
und dann ist da noch der Error: Error:. da muss mal wohl noch was auffangen
