### ISSUE TITLE
projectURL umbenennen

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#38]
> Als Entwickler möchte ich den Projekt-Identifier von projectURL in projectID umbenennen, um einen deskriptiveren Namen zu verwenden, der nicht suggeriert, dass es sich um eine ganze URL handelt, sondern eben bloß um z.B. "cmfcmf/sap-hana".

**Comment by hendraet** [comment]
Gestaltet sich schwieriger als gedacht. Schuld daran ist die Methode loadIssues, die immer aufgerufen wird, wenn man auf eine Methode, Klasse, etc. klickt. Nach der Umbenennung versucht diese mit ProjectID statt ProjectURL zu arbeiten. Das schlägt fehl, da Project ID nicht ordentlich initialisiert ist und zerschießt dann den ganzen Browser
