### ISSUE TITLE
GitHub API anschauen

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#47]
> Als Entwickler möchte ich die GitHub API kennen, um zu verstehen, wie man Anfragen an die API stellen kann und wie diese damit umgeht.
> Als Deliverable sollen 5 neue Ideen rauskommen. :cactus: 
- [x] Authentication
- [x] Rate Limits
- [x] Struktur des Requests
- [x] Struktur des Responses
- [x] (HTTP) Caching
- [x] Welche Informationen zu Issues abrufbar?
- [x] Unterschied Issue, Pull Request
- [x] Scopes des Tokens prüfen
- [x] benötigte Zugriffsrechte für Issues / Assignments
- [x] (Emoji-API)

**Comment by LeaGe** [comment]
https://developer.github.com/v3/

**Comment by frederike-ramin** [comment]
Wirklich neu:
- v3 evtl nicht immer erfüllt --> evtl Accept: `application/vnd.github.v3+json` in Header einfügen
- Zusätzlich zu Titel des Fehlers, die Beschreibung des JSONs mit im Fehlerfenster anzeigen
- Redirects folgen --> auf 301 / 302 reagieren --> der URL folgen
- Bei Bearbeiten von Ressources/Issues: PATCH benutzen, statt alles neu zu senden
- HTTP Cache nutzen, indem man Last-Modified-Tag/Etag in conditional request mitsendet
- In Issue Browser nach Labels filtern (Label als Parameter in URL angegeben) --> nur möglich, wenn man aufhört, Issues zu cachen, sonst müsste man das nachbauen + Labels angeben, wenn man das Issue erstellt
- Reactions auf Issues (obersten Kommentar / Body) und auf Kommentare --> Header squirrel-girl mitsenden
- Prüfen, ob angegebener Assignee Push-Rights hat
- Button zum Öffnen des Issues in externem Web-Browser
- Comments / Issues mit Reactions ergänzen
- Markdown unterstützen
- Locken von Issues, damit keine Kommentare von nicht-push-right-Menschen abgegeben werden können

Praktisch, aber nicht direkt für Kunden:
- Token in Header mitschicken statt an URL anzuhängen
- Scopes von Tokens prüfen
- Alle Issues im Issue Browser anzeigen, idem man nicht nur erste 30 ausgibt, wie es default und jetzt ist, sondern "Seitenwechsel" erlaubt, wo man page=.. als Parameter an die angefragte URL anfügt --> welche Seite als nächstes aufzurufen ist, steht in Header der Antwort, mit Komma getrennt
- Issue in Plain Text zuschicken lassen, statt in MarkDown oder HTML --> nach body_text suchen, statt nach body
- anschauen, ob und welchen User Agent wir mitschicken
- Cache evtl rauswerfen und direkt GitHub API anfragen, nur mit ETag usw als Cache Validation Problem: Fenster mit angezeigten Issues geschlossen --> nicht wiederherstellbar
- Kommentare zu einem Issue anzeigen: An Issue URL /comments anhängen

**Comment by cmfcmf** [comment]
Resultierende User Stories: https://github.com/HPI-SWA-Teaching/SWT16-Project-05/labels/U-Stories%20nach%20Ansehen%20der%20GitHub%20API
