### ISSUE TITLE
UI Bug im Issue Package Browser fixen

### ISSUE THREAD

**Issue by hendraet** [HPI-SWA-Teaching/SWT16-Project-05#54]
Wenn man im IPB Packages nacheinander von unten nach oben ausgewählt hat, bleiben horizontale Linien zurück. Bug tritt auch auf, wenn man lediglich mit der Maus drüber hovert.
![ui_bug_ipb](https://cloud.githubusercontent.com/assets/16731894/15453525/84ee1358-2019-11e6-85f6-d42f654225bf.png)

**Comment by cmfcmf** [comment]
Blubb.
