### ISSUE TITLE
In IssueBrowser nur Repos anzeigen

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#58]
Als User möchte ich eine übersichtlichere Liste der Oberkategorien für Issues haben um nicht dadurch verwirrt zu werden, dass bei mehreren Packages die gleichen Issues angezeigt werden.

**Comment by hendraet** [comment]
Die Umsetzung dieses Features ist sehr problematisch. Die ganze Issue-Verwaltung ist z.Z. nämlich auf Packages und nicht auf Repos ausgelegt. Konkret tritt dabei folgendes Problem auf:
Wenn man im Issues Browser oben das entsprechende Package auswählt, dann wird der String des Pakets ausgeschnitten und damit im repositoryDictionary das entsprechende IssueManagement ausgewählt. Das funktioniert halt nicht mehr, wenn die Packages im Auswahl-String nicht mehr auftauchen.
Es müssten also größere Änderungen vorgenommen werden, um das Problem zu umgehen.
Folgende Lösungen hatte ich im Kopf, allerdings sind diese schwer zu realisieren:
- Einführung eines Dictionaries, was repositories das entsprechende IssueManagement zuordnet. Das ist nicht wirklich möglich, da in einem IssueManagement auch immer der User und der Token gespeichert sind, was für den aktuellen Fall keine Rolle spielen würde, aber im Allgemeinen unsauber wäre.
- Man könnte auch irgendwie umgehen, dass das Package nur am angezeigten String festgemacht wird, aber dazu ist mir bis jetzt noch nichts eingefallen. Allerdings bekomme ich gerade eine Idee, während ich das schreibe.
