### ISSUE TITLE
Tests schreiben

### ISSUE THREAD

**Issue by frederike-ramin** [HPI-SWA-Teaching/SWT16-Project-05#95]
Folgende Tests müssen noch geschrieben werden:
- [x] IIIssue>>labelsAsString
- [x] IssueManagement>>cacheIssues:
- [x] IssueManagement>>closeIssue:
- [x] IssueManagement>>get(My)Issues(forClass:/forMethod:)
- [x] IssueManagement>>webClient Getter/Setter
- [x] GitHubIM>>editIssue: labels:
- [x] GitHubIM>>LoadLabels
- [x] IssueBrowser title, assignee, body, labels Getter/Setter
- [x] IssueBrowser>>closeIssue / issueListMenu:
- [x] IssueBrowser>>openIssueView
- [x] IssueBrowser>>updateLabels
- [x] IssueCreator Smoke
- [x] IssueCreator>>getLabelsOfRepo
- [x] IssueCreator>>labelsAt:
- [x] IssueCreator>>labelsAt: put:
- [x] IssueCreator>>windowWidget/:
- [x] IssueCreator>>labelsSelected/:
- [x] IssueCreator>>methodName
- [x] IssueCreator>>issueClassName
- [x] IssueCreator>>issueClassIsMeta
- [x] Settings>>selectPackage:

Verbesserungen nötig:
- [x] IISettingsUITest>>testInputValidation
- [x] Subclass Responsibilities testen

**Comment by cmfcmf** [comment]
@fniephaus, schau mal:
![image](https://cloud.githubusercontent.com/assets/2145092/17118448/d9549eec-52c0-11e6-8d28-b7accab97702.png)

**Comment by fniephaus** [comment]
Das glaube ich euch nicht 😄
